# Feature Selection Strategy

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [63]:
df = pd.read_csv("C:/Users/galie/DataScience/project/final_data_inc_newstuff.csv")
df.head()

,year,month,cum_week1,wk_atm_p,wk_dew_p,wk_avg_max_tmp,wk_max_tm,wk_avg_tm,wk_min_tm,wk_avg_min_tmp,...,max_y_q_precipitation,q_temp,mean_t,mean_t_d,percipitation,max_y_q_temp,min_y_q_temp,max_y_precipitation,seasonality,per_seasonality
0,2013,1,1,943.729762,18.032500,30.780000,35.7,24.191548,15.8,19.000000,...,84.497143,22.568299,22.5683,17.93779,84.11238,22.568299,17.937794,42.205714,0.164891,-0.248807
1,2013,1,2,941.438810,18.379524,28.671429,36.7,22.999167,15.8,19.442857,...,84.497143,22.568299,22.5683,17.93779,84.11238,22.568299,17.937794,42.205714,0.164891,-0.248807
2,2013,3,9,943.112381,18.795119,27.914286,36.2,22.446429,16.7,19.188571,...,84.497143,21.437083,22.5683,17.93779,84.11238,22.568299,17.937794,42.205714,-0.017274,2.478258
3,2013,9,34,948.730952,13.337143,24.802857,32.0,18.253333,9.2,13.665714,...,84.497143,19.379818,22.5683,17.93779,84.11238,22.568299,17.937794,42.205714,0.386284,-1.105228
4,2013,3,7,942.211667,18.417262,30.442857,35.6,23.951310,15.5,18.720000,...,84.497143,21.437083,22.5683,17.93779,84.11238,22.568299,17.937794,42.205714,-0.017274,2.478258

In [64]:
df['alot_of_patients_yn'] = df['alot_of_patients_yn'].astype('category')

df.dtypes

year                           int64
month                          int64
cum_week1                      int64
wk_atm_p                     float64
wk_dew_p                     float64
wk_avg_max_tmp               float64
wk_max_tm                    float64
wk_avg_tm                    float64
wk_min_tm                    float64
wk_avg_min_tmp               float64
wk_avg_hum                   float64
wk_min_hum                     int64
avg_max_blast_w              float64
max_blast_w                  float64
avg_wind_speed               float64
wk_avg_precipitation         float64
num_patients                   int64
male_perc                      int64
log_num_patients             float64
log_wk_avg_precipitation     float64
dry_week_yn                    int64
alot_of_patients_yn         category
season.x                       int64
ann_mean_tmp                 float64
diurnal_range                float64
mean_diu_range               float64
max_y_temp                   float64
min_y_temp                   float64
annual_range                 float64
Isothermality                float64
mean_temp                    float64
ann_precipitation            float64
monthly_precipitation        float64
min_y_precipitation          float64
q_precipitation              float64
min_y_q_precipitation        float64
max_y_q_precipitation        float64
q_temp                       float64
mean_t                       float64
mean_t_d                     float64
percipitation                float64
max_y_q_temp                 float64
min_y_q_temp                 float64
max_y_precipitation          float64
seasonality                  float64
per_seasonality              float64
dtype: object

In [110]:
# the first 3 ones are just indexes
varSel = pd.DataFrame({'Variable': df.columns[3:46]})
varSel.head()

         Variable
0        wk_atm_p
1        wk_dew_p
2  wk_avg_max_tmp
3       wk_max_tm
4       wk_avg_tm

### create a categorical variable for the checks below (as explained in class)

In [39]:
nm = df.columns[3:46]
nm = nm.append(pd.Index(['alot_of_patients_yn']))
nm

Index(['wk_atm_p', 'wk_dew_p', 'wk_avg_max_tmp', 'wk_max_tm', 'wk_avg_tm',
       'wk_min_tm', 'wk_avg_min_tmp', 'wk_avg_hum', 'wk_min_hum',
       'avg_max_blast_w', 'max_blast_w', 'avg_wind_speed',
       'wk_avg_precipitation', 'num_patients', 'male_perc', 'log_num_patients',
       'log_wk_avg_precipitation', 'dry_week_yn', 'alot_of_patients_yn',
       'season.x', 'ann_mean_tmp', 'diurnal_range', 'mean_diu_range',
       'max_y_temp', 'min_y_temp', 'annual_range', 'Isothermality',
       'mean_temp', 'ann_precipitation', 'monthly_precipitation',
       'min_y_precipitation', 'q_precipitation', 'min_y_q_precipitation',
       'max_y_q_precipitation', 'q_temp', 'mean_t', 'mean_t_d',
       'percipitation', 'max_y_q_temp', 'min_y_q_temp', 'max_y_precipitation',
       'seasonality', 'per_seasonality', 'alot_of_patients_yn'],
      dtype='object')

In [65]:
df.head()

,year,month,cum_week1,wk_atm_p,wk_dew_p,wk_avg_max_tmp,wk_max_tm,wk_avg_tm,wk_min_tm,wk_avg_min_tmp,...,max_y_q_precipitation,q_temp,mean_t,mean_t_d,percipitation,max_y_q_temp,min_y_q_temp,max_y_precipitation,seasonality,per_seasonality
0,2013,1,1,943.729762,18.032500,30.780000,35.7,24.191548,15.8,19.000000,...,84.497143,22.568299,22.5683,17.93779,84.11238,22.568299,17.937794,42.205714,0.164891,-0.248807
1,2013,1,2,941.438810,18.379524,28.671429,36.7,22.999167,15.8,19.442857,...,84.497143,22.568299,22.5683,17.93779,84.11238,22.568299,17.937794,42.205714,0.164891,-0.248807
2,2013,3,9,943.112381,18.795119,27.914286,36.2,22.446429,16.7,19.188571,...,84.497143,21.437083,22.5683,17.93779,84.11238,22.568299,17.937794,42.205714,-0.017274,2.478258
3,2013,9,34,948.730952,13.337143,24.802857,32.0,18.253333,9.2,13.665714,...,84.497143,19.379818,22.5683,17.93779,84.11238,22.568299,17.937794,42.205714,0.386284,-1.105228
4,2013,3,7,942.211667,18.417262,30.442857,35.6,23.951310,15.5,18.720000,...,84.497143,21.437083,22.5683,17.93779,84.11238,22.568299,17.937794,42.205714,-0.017274,2.478258

In [66]:
df2 = df[nm].copy()
df2.head()

,wk_atm_p,wk_dew_p,wk_avg_max_tmp,wk_max_tm,wk_avg_tm,wk_min_tm,wk_avg_min_tmp,wk_avg_hum,wk_min_hum,avg_max_blast_w,...,q_temp,mean_t,mean_t_d,percipitation,max_y_q_temp,min_y_q_temp,max_y_precipitation,seasonality,per_seasonality,alot_of_patients_yn
0,943.729762,18.032500,30.780000,35.7,24.191548,15.8,19.000000,71.235714,25,8.674286,...,22.568299,22.5683,17.93779,84.11238,22.568299,17.937794,42.205714,0.164891,-0.248807,1
1,941.438810,18.379524,28.671429,36.7,22.999167,15.8,19.442857,77.613095,29,10.002857,...,22.568299,22.5683,17.93779,84.11238,22.568299,17.937794,42.205714,0.164891,-0.248807,1
2,943.112381,18.795119,27.914286,36.2,22.446429,16.7,19.188571,81.582143,33,8.442857,...,21.437083,22.5683,17.93779,84.11238,22.568299,17.937794,42.205714,-0.017274,2.478258,1
3,948.730952,13.337143,24.802857,32.0,18.253333,9.2,13.665714,75.723810,23,8.282857,...,19.379818,22.5683,17.93779,84.11238,22.568299,17.937794,42.205714,0.386284,-1.105228,0
4,942.211667,18.417262,30.442857,35.6,23.951310,15.5,18.720000,73.485714,37,7.454286,...,21.437083,22.5683,17.93779,84.11238,22.568299,17.937794,42.205714,-0.017274,2.478258,1

## Multivariable Analysis

In [111]:
### drop na
df2 = df2.dropna()

In [112]:
## remove unnecessary vars
X = df2.iloc[:,:-1]
X.head()

,wk_atm_p,wk_dew_p,wk_avg_max_tmp,wk_max_tm,wk_avg_tm,wk_min_tm,wk_avg_min_tmp,wk_avg_hum,wk_min_hum,avg_max_blast_w,...,max_y_q_precipitation,q_temp,mean_t,mean_t_d,percipitation,max_y_q_temp,min_y_q_temp,max_y_precipitation,seasonality,per_seasonality
0,943.729762,18.032500,30.780000,35.7,24.191548,15.8,19.000000,71.235714,25,8.674286,...,84.497143,22.568299,22.5683,17.93779,84.11238,22.568299,17.937794,42.205714,0.164891,-0.248807
1,941.438810,18.379524,28.671429,36.7,22.999167,15.8,19.442857,77.613095,29,10.002857,...,84.497143,22.568299,22.5683,17.93779,84.11238,22.568299,17.937794,42.205714,0.164891,-0.248807
2,943.112381,18.795119,27.914286,36.2,22.446429,16.7,19.188571,81.582143,33,8.442857,...,84.497143,21.437083,22.5683,17.93779,84.11238,22.568299,17.937794,42.205714,-0.017274,2.478258
3,948.730952,13.337143,24.802857,32.0,18.253333,9.2,13.665714,75.723810,23,8.282857,...,84.497143,19.379818,22.5683,17.93779,84.11238,22.568299,17.937794,42.205714,0.386284,-1.105228
4,942.211667,18.417262,30.442857,35.6,23.951310,15.5,18.720000,73.485714,37,7.454286,...,84.497143,21.437083,22.5683,17.93779,84.11238,22.568299,17.937794,42.205714,-0.017274,2.478258

In [113]:
y = df2.iloc[:,-1:]
print([X.shape,y.shape])

[(310, 43), (310, 1)]

### Variable Selection using LASSO (L1 penalization)

In [114]:
from sklearn.linear_model import Lasso
from sklearn.feature_selection import SelectFromModel

lassomod = Lasso(alpha=0.01).fit(X, y)

In [115]:
model = SelectFromModel(lassomod, prefit=True)
model.get_support()

array([ True, False, False, False, False, False, False,  True,  True,
       False, False, False, False, False, False,  True, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False,  True, False, False, False, False, False])

In [116]:
varSel['Lasso'] = model.get_support().astype('int64')
varSel

                    Variable  Lasso
0                   wk_atm_p      1
1                   wk_dew_p      0
2             wk_avg_max_tmp      0
3                  wk_max_tm      0
4                  wk_avg_tm      0
5                  wk_min_tm      0
6             wk_avg_min_tmp      0
7                 wk_avg_hum      1
8                 wk_min_hum      1
9            avg_max_blast_w      0
10               max_blast_w      0
11            avg_wind_speed      0
12      wk_avg_precipitation      0
13              num_patients      0
14                 male_perc      0
15          log_num_patients      1
16  log_wk_avg_precipitation      0
17               dry_week_yn      0
18       alot_of_patients_yn      1
19                  season.x      0
20              ann_mean_tmp      0
21             diurnal_range      0
22            mean_diu_range      0
23                max_y_temp      0
24                min_y_temp      0
25              annual_range      0
26             Isothermality      0
27                 mean_temp      0
28         ann_precipitation      0
29     monthly_precipitation      1
30       min_y_precipitation      0
31           q_precipitation      0
32     min_y_q_precipitation      0
33     max_y_q_precipitation      0
34                    q_temp      0
35                    mean_t      0
36                  mean_t_d      0
37             percipitation      1
38              max_y_q_temp      0
39              min_y_q_temp      0
40       max_y_precipitation      0
41               seasonality      0
42           per_seasonality      0

### Variable Selection using Random Forest

In [117]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel

rfmod = RandomForestClassifier().fit(X, y)
#rfmod.feature_importances_

<ipython-input-117-41d4b3eec1f3>:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rfmod = RandomForestClassifier().fit(X, y)

In [118]:
model = SelectFromModel(rfmod, prefit=True)
model.get_support()

array([False,  True, False, False, False, False, False, False, False,
       False, False, False, False,  True, False,  True, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False, False,  True, False,
       False, False, False, False, False, False, False])

In [119]:
varSel['RandomForest'] = model.get_support().astype('int64')
varSel

                    Variable  Lasso  RandomForest
0                   wk_atm_p      1             0
1                   wk_dew_p      0             1
2             wk_avg_max_tmp      0             0
3                  wk_max_tm      0             0
4                  wk_avg_tm      0             0
5                  wk_min_tm      0             0
6             wk_avg_min_tmp      0             0
7                 wk_avg_hum      1             0
8                 wk_min_hum      1             0
9            avg_max_blast_w      0             0
10               max_blast_w      0             0
11            avg_wind_speed      0             0
12      wk_avg_precipitation      0             0
13              num_patients      0             1
14                 male_perc      0             0
15          log_num_patients      1             1
16  log_wk_avg_precipitation      0             0
17               dry_week_yn      0             0
18       alot_of_patients_yn      1             1
19                  season.x      0             0
20              ann_mean_tmp      0             0
21             diurnal_range      0             0
22            mean_diu_range      0             0
23                max_y_temp      0             0
24                min_y_temp      0             0
25              annual_range      0             0
26             Isothermality      0             0
27                 mean_temp      0             0
28         ann_precipitation      0             0
29     monthly_precipitation      1             0
30       min_y_precipitation      0             0
31           q_precipitation      0             1
32     min_y_q_precipitation      0             0
33     max_y_q_precipitation      0             0
34                    q_temp      0             1
35                    mean_t      0             0
36                  mean_t_d      0             0
37             percipitation      1             0
38              max_y_q_temp      0             0
39              min_y_q_temp      0             0
40       max_y_precipitation      0             0
41               seasonality      0             0
42           per_seasonality      0             0

### Variable Selection using Gradient Boosting classification

In [120]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.feature_selection import SelectFromModel

gbmod = GradientBoostingClassifier().fit(X, y)

C:\Users\galie\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)

In [121]:
model = SelectFromModel(gbmod, prefit=True)
model.get_support()

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False,  True, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [122]:
varSel['GradientBoost'] = model.get_support().astype('int64')
varSel

                    Variable  Lasso  RandomForest  GradientBoost
0                   wk_atm_p      1             0              0
1                   wk_dew_p      0             1              0
2             wk_avg_max_tmp      0             0              0
3                  wk_max_tm      0             0              0
4                  wk_avg_tm      0             0              0
5                  wk_min_tm      0             0              0
6             wk_avg_min_tmp      0             0              0
7                 wk_avg_hum      1             0              0
8                 wk_min_hum      1             0              0
9            avg_max_blast_w      0             0              0
10               max_blast_w      0             0              0
11            avg_wind_speed      0             0              0
12      wk_avg_precipitation      0             0              0
13              num_patients      0             1              1
14                 male_perc      0             0              0
15          log_num_patients      1             1              1
16  log_wk_avg_precipitation      0             0              0
17               dry_week_yn      0             0              0
18       alot_of_patients_yn      1             1              1
19                  season.x      0             0              0
20              ann_mean_tmp      0             0              0
21             diurnal_range      0             0              0
22            mean_diu_range      0             0              0
23                max_y_temp      0             0              0
24                min_y_temp      0             0              0
25              annual_range      0             0              0
26             Isothermality      0             0              0
27                 mean_temp      0             0              0
28         ann_precipitation      0             0              0
29     monthly_precipitation      1             0              0
30       min_y_precipitation      0             0              0
31           q_precipitation      0             1              0
32     min_y_q_precipitation      0             0              0
33     max_y_q_precipitation      0             0              0
34                    q_temp      0             1              0
35                    mean_t      0             0              0
36                  mean_t_d      0             0              0
37             percipitation      1             0              0
38              max_y_q_temp      0             0              0
39              min_y_q_temp      0             0              0
40       max_y_precipitation      0             0              0
41               seasonality      0             0              0
42           per_seasonality      0             0              0

### Variable Selection using SVM classification

In [123]:
from sklearn.svm import LinearSVC
from sklearn.feature_selection import SelectFromModel

svmmod = LinearSVC(C=0.01, penalty="l1",dual=False).fit(X, y)

C:\Users\galie\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)

In [124]:
model = SelectFromModel(svmmod, prefit=True)
model.get_support()

array([ True, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True, False, False, False, False, False])

In [125]:
varSel['SVM'] = model.get_support().astype('int64')
varSel

                    Variable  Lasso  RandomForest  GradientBoost  SVM
0                   wk_atm_p      1             0              0    1
1                   wk_dew_p      0             1              0    0
2             wk_avg_max_tmp      0             0              0    0
3                  wk_max_tm      0             0              0    0
4                  wk_avg_tm      0             0              0    0
5                  wk_min_tm      0             0              0    0
6             wk_avg_min_tmp      0             0              0    0
7                 wk_avg_hum      1             0              0    0
8                 wk_min_hum      1             0              0    0
9            avg_max_blast_w      0             0              0    0
10               max_blast_w      0             0              0    0
11            avg_wind_speed      0             0              0    0
12      wk_avg_precipitation      0             0              0    0
13              num_patients      0             1              1    1
14                 male_perc      0             0              0    0
15          log_num_patients      1             1              1    0
16  log_wk_avg_precipitation      0             0              0    0
17               dry_week_yn      0             0              0    0
18       alot_of_patients_yn      1             1              1    0
19                  season.x      0             0              0    0
20              ann_mean_tmp      0             0              0    0
21             diurnal_range      0             0              0    0
22            mean_diu_range      0             0              0    0
23                max_y_temp      0             0              0    0
24                min_y_temp      0             0              0    0
25              annual_range      0             0              0    0
26             Isothermality      0             0              0    0
27                 mean_temp      0             0              0    0
28         ann_precipitation      0             0              0    0
29     monthly_precipitation      1             0              0    0
30       min_y_precipitation      0             0              0    0
31           q_precipitation      0             1              0    0
32     min_y_q_precipitation      0             0              0    0
33     max_y_q_precipitation      0             0              0    0
34                    q_temp      0             1              0    0
35                    mean_t      0             0              0    0
36                  mean_t_d      0             0              0    0
37             percipitation      1             0              0    1
38              max_y_q_temp      0             0              0    0
39              min_y_q_temp      0             0              0    0
40       max_y_precipitation      0             0              0    0
41               seasonality      0             0              0    0
42           per_seasonality      0             0              0    0

### Summarization and Selection of Variables

In [126]:
varSel['Sum'] =  np.sum(varSel,axis=1)
varSel

                    Variable  Lasso  RandomForest  GradientBoost  SVM  Sum
0                   wk_atm_p      1             0              0    1    2
1                   wk_dew_p      0             1              0    0    1
2             wk_avg_max_tmp      0             0              0    0    0
3                  wk_max_tm      0             0              0    0    0
4                  wk_avg_tm      0             0              0    0    0
5                  wk_min_tm      0             0              0    0    0
6             wk_avg_min_tmp      0             0              0    0    0
7                 wk_avg_hum      1             0              0    0    1
8                 wk_min_hum      1             0              0    0    1
9            avg_max_blast_w      0             0              0    0    0
10               max_blast_w      0             0              0    0    0
11            avg_wind_speed      0             0              0    0    0
12      wk_avg_precipitation      0             0              0    0    0
13              num_patients      0             1              1    1    3
14                 male_perc      0             0              0    0    0
15          log_num_patients      1             1              1    0    3
16  log_wk_avg_precipitation      0             0              0    0    0
17               dry_week_yn      0             0              0    0    0
18       alot_of_patients_yn      1             1              1    0    3
19                  season.x      0             0              0    0    0
20              ann_mean_tmp      0             0              0    0    0
21             diurnal_range      0             0              0    0    0
22            mean_diu_range      0             0              0    0    0
23                max_y_temp      0             0              0    0    0
24                min_y_temp      0             0              0    0    0
25              annual_range      0             0              0    0    0
26             Isothermality      0             0              0    0    0
27                 mean_temp      0             0              0    0    0
28         ann_precipitation      0             0              0    0    0
29     monthly_precipitation      1             0              0    0    1
30       min_y_precipitation      0             0              0    0    0
31           q_precipitation      0             1              0    0    1
32     min_y_q_precipitation      0             0              0    0    0
33     max_y_q_precipitation      0             0              0    0    0
34                    q_temp      0             1              0    0    1
35                    mean_t      0             0              0    0    0
36                  mean_t_d      0             0              0    0    0
37             percipitation      1             0              0    1    2
38              max_y_q_temp      0             0              0    0    0
39              min_y_q_temp      0             0              0    0    0
40       max_y_precipitation      0             0              0    0    0
41               seasonality      0             0              0    0    0
42           per_seasonality      0             0              0    0    0

In [127]:
varSel.groupby('Sum')['Variable'].count()

Sum
0    32
1     6
2     2
3     3
Name: Variable, dtype: int64

In [ ]:
### thats not great..

only : monthly_precipitation,q_temp,percipitation,wk_min_hum,wk_dew_p,wk_atm_p had one  or 2 hits..

#### In the next file, I will show the univariate analysis in R and choose the variables to progress with.